# Generated by Django 3.1.7 on 2021-03-23 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='incident_loaction',
            new_name='incident_location',
        ),
    ]
